[package]
name = "stray_texture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion = "0.4.0"
image = "0.24.5"
naga = "0.11.0"

wgpu = {version = "0.15.0", features = ["glsl"]}
